# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application continuous integration
on:
  pull_request:
  push:
    branches: [master, develop]
permissions:
  contents: read
jobs:
  pre_commit_hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.12"
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Run Mypy
        run: |
          pipenv run mypy
      - name: Run Black formatter
        run: |
          pipenv run black --check
      - name: Run Flake8 linter
        run: |
          pipenv run flake8
      - name: Run check imports
        run: |
          pipenv run check_imports